version: '3'

networks:
    backend:

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: always
        container_name: nginx
        volumes:
            - ./:/var/www/yazu_links
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8000:80"
        networks:
            - backend
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: yazu_app
        volumes:
            - ./:/var/www/yazu_links
        links:
            - postgres
            - redis
        depends_on:
            - nginx
            - postgres
            - redis
        environment:
            - DB_CONNECTION=pgsql
            - DB_DATABASE=url_crypt
            - DB_USERNAME=postgres
            - DB_PASSWORD=123
            - CACHE_DRIVER=redis
            - QUEUE_CONNECTION=redis
            - REDIS_CLIENT=predis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - APP_FRONT_URL=hide-url.ru
        networks:
            - backend
    php-queue:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: app_queue
        volumes:
            - ./:/var/www/yazu_links
        depends_on:
            - app
        links:
            - postgres
            - redis
        networks:
            - backend
        command: [ "./docker/entrypoint.sh" ]
#        command: php artisan queue:work
    postgres:
        image: postgres:15.4-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=url_crypt
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
            - ./docker/postgres/storage:/var/lib/postgresql/storage
        ports:
            - "5432:5432"
        networks:
            - backend
    redis:
        restart: always
        image: redis:7.0.12-alpine
        container_name: redis
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "6379:6379"
        networks:
            - backend
